feat: support `as` to change the rendered component
Barbapapazes/nuxt-authorization pull request #33
Opened 2024-11-13 16:44 UTC by maartenvanhunsel

Resolves: https://github.com/Barbapapazes/nuxt-authorization/issues/31

2024-11-13 16:55 UTC, Barbapapazes requested changes

2024-11-13 16:55 UTC, Barbapapazes commented on src/runtime/components/Tag.ts
can you not use this component instead?

https://vuejs.org/api/built-in-special-elements#component

2024-11-13 17:02 UTC, maartenvanhunsel commented on src/runtime/components/Tag.ts
It's quite the same, however I just wanted to give the user the opportunity to use HTML tags optionally.

With Component :is we cannot create an empty <template> and we always have to render a div or another tag

2024-11-19 18:45 UTC, maartenvanhunsel commented on src/runtime/components/Tag.ts
@Barbapapazes so WYT?

2024-11-20 13:46 UTC, Barbapapazes commented on src/runtime/components/Tag.ts
Hey! I'll will have a look!

2024-11-20 14:28 UTC, Barbapapazes approved these changes

2024-11-20 14:29 UTC, merged